"""Generate a dense GeoClaw gauge list along the coastline.

The nested LISFLOOD boundary is built from GeoClaw gauge time series, so gauge spacing sets
how well the alongshore surge structure is resolved at the clip boundary. Gauges are cheap in
GeoClaw, unlike AMR levels, so spacing is the low-cost way to improve the nest.

Gauges are placed on the shoreline contour of the surge-model DEM, then moved a few cells
seaward. A gauge on the land side of the contour dries out at low water and returns bed
elevation instead of a stage, which the boundary builder then has to fill.

Writes a block of `rundata.gaugedata.gauges.append([...])` lines to paste into setrun.py.

    python -m coral.geoclaw.make_gauges --dem SUB_DEM_SAV.asc --spacing-m 100 \\
        --out geoclaw_gauges.py
"""
from __future__ import annotations
import argparse
from pathlib import Path

import numpy as np

from ..emulator.dataset import read_asc


def coastline_points(dem, h, *, sea_level=0.0, spacing_m=100.0, seaward_cells=3,
                     min_len=50, bbox=None):
    """Points along the shoreline contour at `spacing_m`, offset seaward.

    Returns (lon, lat) arrays. `bbox` = [W, E, S, N] keeps only points inside it, so gauges
    can be concentrated on the stretch that feeds the nested clip.
    """
    from skimage import measure
    from scipy import ndimage

    z = np.where(np.isfinite(dem), dem, sea_level - 10.0)
    ny, nx = z.shape
    cs = h["cellsize"]
    # metres per degree; longitude shrinks with latitude
    lat0 = h["yllcorner"] + 0.5 * ny * cs
    m_per_deg_y = 111132.0
    m_per_deg_x = 111320.0 * np.cos(np.radians(lat0))

    sea = z <= sea_level
    # outward normal, from a distance transform of the sea: gradient points landward, so the
    # seaward offset is its negative
    dist = ndimage.distance_transform_edt(~sea)
    gy, gx = np.gradient(dist)

    out = []
    for c in measure.find_contours(z, sea_level):
        if len(c) < min_len:
            continue
        # arc length along the contour, in metres
        d = np.diff(c, axis=0)
        seg = np.hypot(d[:, 0] * cs * m_per_deg_y, d[:, 1] * cs * m_per_deg_x)
        s = np.concatenate([[0.0], np.cumsum(seg)])
        if s[-1] < spacing_m:
            continue
        want = np.arange(0.0, s[-1], spacing_m)
        rr = np.interp(want, s, c[:, 0])
        cc = np.interp(want, s, c[:, 1])
        for r, col in zip(rr, cc):
            ri, ci = int(np.clip(round(r), 0, ny - 1)), int(np.clip(round(col), 0, nx - 1))
            n = np.hypot(gy[ri, ci], gx[ri, ci])
            if n > 1e-9:                      # step seaward along the negative gradient
                r -= seaward_cells * gy[ri, ci] / n
                col -= seaward_cells * gx[ri, ci] / n
            lon = h["xllcorner"] + (col + 0.5) * cs
            lat = h["yllcorner"] + (ny - r - 0.5) * cs
            out.append((lon, lat))

    pts = np.array(out) if out else np.zeros((0, 2))
    if bbox is not None and len(pts):
        w, e, s_, n_ = bbox
        keep = (pts[:, 0] >= w) & (pts[:, 0] <= e) & (pts[:, 1] >= s_) & (pts[:, 1] <= n_)
        pts = pts[keep]
    return pts


def write_setrun_block(pts, out, *, t1=0.0, t2=1e9, start_id=1, min_sep_m=0.0):
    """Write the gauges.append lines. `min_sep_m` thins points that crowd together where
    contours meet."""
    if min_sep_m > 0 and len(pts):
        keep, last = [], None
        for p in pts:
            if last is None or np.hypot((p[0] - last[0]) * 95000.0,
                                        (p[1] - last[1]) * 111132.0) >= min_sep_m:
                keep.append(p); last = p
        pts = np.array(keep)

    lines = ["# Generated by coral.geoclaw.make_gauges. Paste into setrun.py.",
             "# gauges.append([id, x, y, t1, t2])"]
    for i, (lon, lat) in enumerate(pts, start=start_id):
        lines.append(f"rundata.gaugedata.gauges.append([{i}, {lon:.6f}, {lat:.6f}, "
                     f"{t1:g}, {t2:g}])")
    Path(out).write_text("\n".join(lines) + "\n")
    print(f"{len(pts)} gauges -> {out}")
    return pts


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dem", required=True, help="surge-model DEM (ascii grid)")
    ap.add_argument("--spacing-m", type=float, default=100.0)
    ap.add_argument("--sea-level", type=float, default=0.0)
    ap.add_argument("--seaward-cells", type=int, default=3)
    ap.add_argument("--bbox", nargs=4, type=float, default=None, metavar=("W", "E", "S", "N"))
    ap.add_argument("--min-sep-m", type=float, default=0.0)
    ap.add_argument("--start-id", type=int, default=1)
    ap.add_argument("--out", default="geoclaw_gauges.py")
    a = ap.parse_args()
    dem, h = read_asc(a.dem)
    pts = coastline_points(dem, h, sea_level=a.sea_level, spacing_m=a.spacing_m,
                           seaward_cells=a.seaward_cells, bbox=a.bbox)
    write_setrun_block(pts, a.out, start_id=a.start_id, min_sep_m=a.min_sep_m)


if __name__ == "__main__":
    main()
